=== Andreu-08/LMSGI/XML/EJERCICIOS_XML_DTD/ENTREGADO/Exercicis DTD Basics/eleccions.dtd
<!ELEMENT eleccions (descripcio, dades, resultats)>
        <!ELEMENT descripcio (#PCDATA)>
        <!ELEMENT dades (data, cens, abstencio, blancs)>
        <!ELEMENT data (#PCDATA)>
        <!ELEMENT cens (#PCDATA)>
        <!ELEMENT abstencio (#PCDATA)>
        <!ELEMENT blancs (#PCDATA)>
        <!ELEMENT resultats (partit)*>
        <!ELEMENT partit (nom, vots)>
        <!ELEMENT nom (#PCDATA)>
        <!ELEMENT vots (#PCDATA)>

=== Andreu-08/LMSGI/XML/EJERCICIOS_XML_DTD/ENTREGADO/Exercicis DTD Basics/eleccions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eleccions SYSTEM "eleccions.dtd">

<eleccions> 
    <descripcio>Marcianes 2010</descripcio>
    <dades>
        <data>2010-11-29</data>
        <cens>500</cens>
        <abstencio>450</abstencio>
        <blancs>12</blancs>
    </dades>
    <resultats>
        <partit>
            <nom>Partit Vermell</nom>
            <vots>8</vots>
        </partit>
        <partit>
            <nom>Marcians Units</nom>
            <vots>14</vots>
        </partit>
        <partit>
            <nom>Coordinadora per un planeta verd</nom>
            <vots>5</vots>
        </partit>
        <partit>
            <nom>Partit de Phobos</nom>
            <vots>5</vots>
        </partit>
        <partit>
            <nom>Esquerra Marciana</nom>
            <vots>6</vots>
        </partit>        
    </resultats>    
</eleccions>
