=== Andreu-08/LMSGI/XML/PROYECTO XML/ProjecteT1-P1-AOR/ProjecteT1-P1-AOR.dtd
<!ELEMENT biblioteca (libro*, autor*)>
        <!ELEMENT libro (titulo,fecha_publicacion, genero, editorial)>
        <!ELEMENT autor (nombre, genero_principal, nacionalidad, fecha_nacimiento)>
        <!ELEMENT titulo (#PCDATA)>
        <!ELEMENT fecha_publicacion (#PCDATA)>
        <!ELEMENT genero (#PCDATA)>
        <!ELEMENT editorial (#PCDATA)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT genero_principal (#PCDATA)>
        <!ELEMENT nacionalidad (#PCDATA)>
        <!ELEMENT fecha_nacimiento (#PCDATA)>
        <!ELEMENT id (#PCDATA)>

        <!ATTLIST libro idref IDREF #REQUIRED>
        <!ATTLIST libro portada (jpg | png) #REQUIRED>
        <!ATTLIST autor foto (jpg | png) #REQUIRED>
        <!ATTLIST autor id ID #REQUIRED>
        <!ATTLIST autor pagina_web CDATA #IMPLIED>
        <!ATTLIST genero id ID #REQUIRED>
        <!ATTLIST genero_principal idref IDRED #REQUIRED>
        <!ATTLIST editorial URL #IMPLIED>

=== Andreu-08/LMSGI/XML/PROYECTO XML/ProjecteT1-P1-AOR/ProjecteT1-P1-AOR.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE biblioteca SYSTEM "ProjecteT1-P1-AOR.dtd"[]>

 <biblioteca>
    <libro idref="" portada="jpg">
        <titulo></titulo>
        <fecha_publicacion></fecha_publicacion>
        <genero id=""></genero>
        <editorial URL=""></editorial>
    </libro>
    <autor foto="" id="">
        <nombre></nombre>
        <genero_principal idref=""></genero_principal>
        <nacionalidad></nacionalidad>
        <fecha_nacimiento></fecha_nacimiento>
    </autor>
    <autor foto="" id="">
        <nombre></nombre>
        <genero_principal idref=""></genero_principal>
        <nacionalidad></nacionalidad>
        <fecha_nacimiento></fecha_nacimiento>
    </autor>
    <autor foto="" id="">
        <nombre></nombre>
        <genero_principal idref=""></genero_principal>
        <nacionalidad></nacionalidad>
        <fecha_nacimiento></fecha_nacimiento>
    </autor>
</biblioteca>
