=== Andreu-08/LMSGI/XML/PRACTICAS XML-DTD/ENTREGADO/P2 FACTURA/P2_FACTURA.dtd
<!ELEMENT facturas (factura)*>
        <!ELEMENT factura (emisor, client, detalles)>
        <!ATTLIST factura numero NMTOKEN #REQUIRED>
        <!ATTLIST factura fecha CDATA #REQUIRED>
        <!ELEMENT emisor (nom, telefon)>
        <!ELEMENT client (nom, telefon)>
        <!ELEMENT nom (#PCDATA)>
        <!ELEMENT telefon (#PCDATA)>
        <!ATTLIST emisor CIF NMTOKEN #REQUIRED>
        <!ATTLIST client CIF NMTOKEN #REQUIRED>
        <!ELEMENT detalles (linea)+>
        <!ATTLIST detalles importe CDATA #REQUIRED>
        <!ELEMENT linea (descripcion, cantidad, oferta, pvp)>
        <!ATTLIST linea codarticulo ID #REQUIRED>
        <!ATTLIST linea tipo (libro | DVD | varios) #IMPLIED>
        <!ELEMENT descripcion (#PCDATA)>
        <!ELEMENT cantidad (#PCDATA)>
        <!ELEMENT oferta EMPTY>
        <!ATTLIST oferta  oferta (SI | NO) "SI">
        <!ELEMENT pvp (#PCDATA)>
        ]>

=== Andreu-08/LMSGI/XML/PRACTICAS XML-DTD/ENTREGADO/P2 FACTURA/P2_FACTURA.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE facturas SYSTEM "P2_FACTURA.dtd" []>

<facturas>
    <factura numero="27" fecha="18/12/2025">
        <emisor CIF="44555666B">
            <nom>LIBRERIA PEREZ</nom>
            <telefon>777888999</telefon>
        </emisor>
        <client CIF="33111222A">
            <nom>Bibliote txantrea</nom>
            <telefon>333999444</telefon>
        </client>
        <detalles importe="85€">
            <linea codarticulo="AW7" tipo="libro">
                <descripcion>Analitica web 2.0</descripcion>
                <cantidad>1</cantidad>
                <oferta oferta="SI"/>
                <pvp>25€</pvp>
            </linea>
            <linea codarticulo="CP5" tipo="DVD">
                <descripcion>Curso HTML</descripcion>
                <cantidad>2</cantidad>
                <oferta oferta="NO"/>
                <pvp>30€</pvp>
            </linea>
        </detalles>
    </factura>
</facturas>
