=== Andreu-08/LMSGI/XML/PRACTICAS XML-DTD/ENTREGADO/P4_BLOG/P4_BLOG_AndreuOrenga.dtd
<!ELEMENT blog (categoria+)>
        <!ELEMENT categoria (noticia | event)+>
        <!ATTLIST categoria
                id  ID #REQUIRED
                nom CDATA #REQUIRED>
        <!ELEMENT noticia (text, titol, data, hora, comentari, imatge*, etiqueta*)>
        <!ATTLIST noticia
                id ID #REQUIRED
                URL CDATA #REQUIRED
                puntuacio ( 0 | 1 | 2 | 3 ) #IMPLIED>
        <!ELEMENT titol (#PCDATA)>
        <!ELEMENT text (#PCDATA)>
        <!ELEMENT comentari (text, data, hora, autor?)>
        <!ELEMENT autor (#PCDATA)>
        <!ELEMENT data (#PCDATA)>
        <!ELEMENT hora (#PCDATA)>
        <!ELEMENT imatge EMPTY>
        <!ATTLIST imatge URL (jpg | png | bmp) #IMPLIED>
        <!ELEMENT etiqueta (#PCDATA)>
        <!ELEMENT event (titol, lloc,text, data, hora, (hora_fi, data_fi)?)>
        <!ATTLIST event
                id ID #REQUIRED
                activitat (pagament | gratuita) #IMPLIED
                URL CDATA #REQUIRED>
        <!ELEMENT lloc (#PCDATA)>
        <!ELEMENT hora_fi (#PCDATA)>
        <!ELEMENT data_fi (#PCDATA)>
        ]>

=== Andreu-08/LMSGI/XML/PRACTICAS XML-DTD/ENTREGADO/P4_BLOG/P4_BLOG_AndreuOrenga.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE blog SYSTEM "P4_BLOG_AndreuOrenga.dtd"[]>
<blog>
    <categoria id="23" nom="nom categoria">
        <event id="45" URL="url event" activitat="gratuita">
            <titol>titol event</titol>
            <lloc>lloc event</lloc>
            <text>descripcio event</text>
            <data>data event</data>
            <hora>hora event</hora>
            <data_fi>data fi event</data_fi>
            <hora_fi>hora fi event</hora_fi>
        </event>
    </categoria>
    <categoria id="56" nom="nom categoria">
        <noticia id="100" URL="url noticia" puntuacio="3">
            <text>descripcio noticia</text>
            <titol>titol noticia</titol>
            <data>data noticia</data>
            <hora>hora noticia</hora>
            <imatge URL="png"/>
            <comentari>
                <text>text comentari</text>
                <data>data comentari</data>
                <hora>hora comentari</hora>
                <autor>aututor (pot no estar)</autor>
            </comentari>
        </noticia>
    </categoria>
</blog>
