<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ropa [
    <!ELEMENT ropa (nombre, color*)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT color (#PCDATA)>
]>
<ropa>
    <nombre>guante</nombre>
        <color>rojo</color>
        <color>blanco</color>
    <nombre>bufanda</nombre>
        <color>verde</color>
        <color>azul</color>
</ropa>